version: "3"

volumes:
  redis_data:
    driver: local

services:
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    ports:
      - "6686:6379"
    command: "redis-server --appendonly yes"
    volumes:
      - redis_data:/data